# Generated by Django 4.2 on 2023-05-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloglist',
            fields=[
                ('Blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('Author_name', models.CharField(max_length=200)),
                ('Publish_date', models.DateField()),
                ('Blog_category', models.CharField(max_length=300)),
                ('Blog_title', models.CharField(max_length=400)),
                ('Blog_caption', models.CharField(max_length=500)),
                ('Blog_image', models.ImageField(upload_to='blogs')),
            ],
        ),
    ]
