# Generated by Django 4.2 on 2023-05-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_alter_bloglist_blog_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloglist',
            name='Blog_image',
        ),
        migrations.AddField(
            model_name='bloglist',
            name='Blog_img',
            field=models.ImageField(blank=True, null=True, upload_to='blogs'),
        ),
    ]
