# Generated by Django 4.2 on 2023-06-01 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_remove_bloglist_blog_image_bloglist_blog_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglist',
            name='Publish_date',
            field=models.DateTimeField(),
        ),
    ]
